import { Poppins } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/layOuts/Navbar";
import Footer from "@/components/layOuts/Footer";

const poppins = Poppins({
	weight: ["100", "200", "400", "500", "600", "800"],
});

export const fontBangla = localFont({
	src: "../fonts/mayaboti-normal.ttf",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${poppins.className} antialiased`}>
				<header className="py-2 container mx-auto">
					<Navbar />
				</header>
				<main className="py-2 container mx-auto">{children}</main>
				<footer>
					<Footer />
				</footer>
			</body>
		</html>
	);
}
