import Products from "@/components/home/Products";
import React from "react";

export const metadata = {
	title: "All Products",
	description: "Generated by create next app",
};

const ProductPage = () => {
	return (
		<section className="pb-20">
			<Products />
		</section>
	);
};

export default ProductPage;
